import Head from 'next/head'
import Image from 'next/image'
import Axios from 'axios'
import React, { useState , useEffect, useMemo} from 'react';
import Link from 'next/link';


export default function Home(props) {
  const [itemList, setitemList] = useState([]);
  useEffect(() => {
    setitemList(props.data.results);
  }, []);

  const items = props.data;
  console.log(itemList);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className='item_list'>
        {itemList.map((item) => (
          <div key={item.id} className="item">
            <Link href={`/detail/${item.id}`}>
              <img src={`https://image.tmdb.org/t/p/w500/${item.poster_path}`}/>
              <div className="cnt">
                  <span className="subject">{item.original_title}</span>
                  <span className="date">{item.release_date}</span>
              </div>
            </Link>
          </div>
        ))}
        </div>
      </div>

      <style jsx>{`
        .item_list{display:flex;flex-wrap:wrap;padding:15px;}
        .item_list .item{width:49%;}
        .item_list .item:nth-child(2n){margin-left:2%;}
        .item_list .item:nth-child(n + 3){margin-top:5%}
        .item_list .item img{width:100%;}
        .item_list .item .cnt{margin-top:10px;}
        .item_list .item .cnt .subject{display:block;font-size:16px;color:#000;font-weight:600;}
        .item_list .item .cnt .date{font-size:12px;color:#555;display:block;margin-top:5px;}
      `}</style>
    </>
    
  )
}

export const getServerSideProps = async () => {
  const res = await Axios.get(process.env.LIST_API_URL)
  return {
      props: { data: res.data },
  };
};